[platformio]
src_dir = firmware/src

[env:Robot]
platform = espressif32
board = esp32dev
framework = arduino
src_filter = +<*> -<Camera.cpp>

platform_packages =
   framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

lib_deps =
    workloads/SCServo@^1.0.1

[env:Camera]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
src_filter = +<Camera.cpp>